// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU8P2Fd34ymLWBYWDlQfZuImyJh0gmASA',
    appId: '1:931250217735:web:0726820bfd0fcd4fa41ba2',
    messagingSenderId: '931250217735',
    projectId: 'memorialapp-b1ccf',
    authDomain: 'memorialapp-b1ccf.firebaseapp.com',
    storageBucket: 'memorialapp-b1ccf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLAoxLjg3qgEMWerskWP-Mz6F6sBkpMb8',
    appId: '1:931250217735:android:8cc69558940e90baa41ba2',
    messagingSenderId: '931250217735',
    projectId: 'memorialapp-b1ccf',
    storageBucket: 'memorialapp-b1ccf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbFfEGZhrCzbdx2zxRpuvabjwB5TLx2Ow',
    appId: '1:931250217735:ios:19df5a001f58f55da41ba2',
    messagingSenderId: '931250217735',
    projectId: 'memorialapp-b1ccf',
    storageBucket: 'memorialapp-b1ccf.firebasestorage.app',
    iosClientId: '931250217735-nvlatv0qvvjona23ldtgjk47f1eonn5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.arbolitos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbFfEGZhrCzbdx2zxRpuvabjwB5TLx2Ow',
    appId: '1:931250217735:ios:19df5a001f58f55da41ba2',
    messagingSenderId: '931250217735',
    projectId: 'memorialapp-b1ccf',
    storageBucket: 'memorialapp-b1ccf.firebasestorage.app',
    iosClientId: '931250217735-nvlatv0qvvjona23ldtgjk47f1eonn5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.arbolitos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU8P2Fd34ymLWBYWDlQfZuImyJh0gmASA',
    appId: '1:931250217735:web:9518b199c9f5f2d5a41ba2',
    messagingSenderId: '931250217735',
    projectId: 'memorialapp-b1ccf',
    authDomain: 'memorialapp-b1ccf.firebaseapp.com',
    storageBucket: 'memorialapp-b1ccf.firebasestorage.app',
  );

}